[package]
name = "rustweet"
version = "0.2.0"
authors = [ "Dan Chiarlone <danilochiarlone@gmail.com>" ]
edition = "2018"

[dependencies]
http = "0.1"
now_lambda = "*"
postgres = "0.17.2"

[[bin]]
name = "index"
path = "/Users/carol/Documents/code/rust/rustweet/backend/index.rs"
